### ISSUE TITLE
Commented out sections in TPCC

### ISSUE THREAD

**Issue by ghost** [yxymit/DBx1000#11]
Hi, I'm looking at DBx1000's implementation of "new order" transactions in TPCC, and came across the following line:

https://github.com/yxymit/DBx1000/blob/fda3950a1837f5d75e46b5aaeb550731d40c3ac0/benchmarks/tpcc_txn.cpp#L424

The commented-out section that comes below inserts to the order line table, which is required by TPCC. Is it a bug?

It also appears to me that the benchmarks in DBx1000 don't exercise `insert_row()` in any index structures, but the indexes themselves seem functional. Is this intended?

**Comment by yxymit** [comment]
Hi Yihe,

We disabled inserts in TPC-C in order to keep the memory footprint low. We found that with inserts, the program can quickly run out of memory. Disabling inserts is ok for us since inserts were not the main focus of our previous research. If you want to study performance for indexes, you should uncomment those lines. The hash index should work properly with inserts/deletes. We haven't tested the B-tree index for a while; so be careful with B-tree since there might be bugs. 

Best,
Xiangyao

**Comment by ghost** [comment]
Thanks for the clarification Xiangyao!
